"""Users router (admin-only; plan section 27).

The bearer token from app/api/security.py is the API's admin credential: it is
generated by the deployment (or on first start) and never exposed to Gradio
sessions, which keep using the in-process service layer and the admin panel.
"""
from fastapi import APIRouter, Depends

from app.api.security import require_api_token
from app.services import user_service

router = APIRouter(
    prefix="/api/v1/users",
    tags=["users"],
    dependencies=[Depends(require_api_token)],
)


@router.get("")
async def list_users():
    return [{"username": u["username"], "role": u["role"]} for u in user_service.list_users()]
