"""Alembic environment (plan §4.3 Step 2).

Two deliberate choices:

* **The URL comes from the application, not from ``alembic.ini``.** Migrations
  must run against the same database the service uses, so
  :func:`fiximg.infrastructure.db.engine.resolve_database_path` is the single
  source of truth — including its fail-fast behaviour for an unsupported scheme.
* **``target_metadata`` is None.** The schema is written by hand rather than
  autogenerated: the repositories rely on SQLite-specific DDL (partial unique
  indexes, ``json_group_array``, ``BEGIN IMMEDIATE``) that autogenerate cannot
  reproduce faithfully, and a wrong ``--autogenerate`` output is worse than no
  autogenerate at all.

Offline mode (``alembic upgrade head --sql``) is supported for review.
"""
from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# The package lives under src/; alembic.ini's prepend_sys_path covers the CLI
# path, and this covers programmatic use.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(PROJECT_ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers` defaults to True, which silences every logger that
    # already exists — including the application's own. A process that ran a migration
    # programmatically (an embedder, a test, `fiximg-db upgrade` inside the API) kept
    # serving requests with `fiximg.*` loggers disabled and emitted no logs at all,
    # which reads like a working service with logging turned off by choice.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

#: No autogenerate — see the module docstring.
target_metadata = None


def database_url() -> str:
    """The SQLAlchemy URL for the database the application will use."""
    from fiximg.infrastructure.db.engine import resolve_database

    configured = os.environ.get("FIXIMG_DATABASE_URL", "").strip()
    kind, target = resolve_database(configured or None)
    if kind == "postgresql":
        # SQLAlchemy's psycopg driver spelling.
        return target.replace("postgresql://", "postgresql+psycopg://", 1) \
            if target.startswith("postgresql://") else target
    if target == ":memory:":
        return "sqlite://"
    # SQLAlchemy wants forward slashes and an absolute path for sqlite.
    return "sqlite:///" + target.replace("\\", "/")


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting (``--sql``)."""
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # SQLite cannot ALTER most things in place; batch mode rewrites the table
        # instead, which is what makes downgrade work at all.
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect and apply migrations in a transaction."""
    section = config.get_section(config.config_ini_section) or {}
    section["sqlalchemy.url"] = database_url()

    connectable = engine_from_config(
        section, prefix="sqlalchemy.", poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
