"""Users router (admin-only; plan §3.8).

The bearer token from :mod:`fiximg.api.security` is the API's admin credential:
it is generated by the deployment (or on first start) and never exposed to
Gradio sessions, which keep using the in-process service layer and admin panel.
"""
from fastapi import APIRouter, Depends

from fiximg.api.dependencies import Principal, require_admin
from fiximg.api.schemas.user import UserCreateRequest, UserUpdateRequest, UserView
from fiximg.application import auth_service as user_service
from fiximg.domain.errors import InvalidRequestError

router = APIRouter(prefix="/api/v1/users", tags=["users"])


def _view(record: dict) -> UserView:
    return UserView(
        username=record.get("username", ""),
        role=record.get("role") or "user",
        status=record.get("status"),
        created_at=record.get("created_at"),
    )


@router.get("", response_model=list[UserView], summary="List users")
async def list_users(_principal: Principal = Depends(require_admin)):
    return [
        UserView(username=u["username"], role=u.get("role") or "user")
        for u in user_service.list_users()
    ]


@router.post("", response_model=UserView, status_code=201, summary="Create a user")
async def create_user(body: UserCreateRequest, _principal: Principal = Depends(require_admin)):
    if not user_service.create_user(body.username, body.password, role=body.role):
        raise InvalidRequestError(
            f"User '{body.username}' already exists",
            code="USER_EXISTS",
            status_code=409,
        )
    return _view(user_service.get_user(body.username) or {"username": body.username,
                                                         "role": body.role})


@router.patch("/{username}", response_model=UserView, summary="Update a user")
async def update_user(
    username: str,
    body: UserUpdateRequest,
    _principal: Principal = Depends(require_admin),
):
    if body.password is None and body.role is None:
        raise InvalidRequestError("Nothing to update: provide password and/or role")
    if not user_service.get_user(username):
        raise InvalidRequestError(
            f"User '{username}' not found", code="USER_NOT_FOUND", status_code=404
        )
    user_service.update_user(username, password=body.password, role=body.role)
    return _view(user_service.get_user(username) or {"username": username})


@router.delete("/{username}", status_code=204, summary="Delete a user")
async def delete_user(username: str, _principal: Principal = Depends(require_admin)):
    if not user_service.get_user(username):
        raise InvalidRequestError(
            f"User '{username}' not found", code="USER_NOT_FOUND", status_code=404
        )
    user_service.delete_user(username)
    return None
