"""Weight file integrity self-check (P1-②).

Motivation: project weights (*.pth / *.pt / *.dat) are large, untracked by git, and never integrity-checked. Corrupted or replaced weights would silently produce wrong results or crash models, which is hard to diagnose. This module verifies weights against a known baseline manifest at server startup, refusing to start when missing or tampered, with explicit errors.

Design:
- The baseline manifest config/weights_manifest.json is generated by this module's generate command and committed, serving as a tamper-evident baseline (hash only, no weight data).
- verify_weights() runs once at startup (weights are static files that do not change at runtime), using a fail-fast policy.
- If the manifest is missing, prompt to generate it first; any missing file or hash mismatch raises an exception.

⚠️ Limitation: the manifest itself needs protection (not secret, but should be controlled along with the weights). This check detects accidental corruption/incorrect replacement, not deliberate attacks that also tamper with the manifest.
"""
import hashlib
import json
import os
from datetime import datetime, timezone

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST_PATH = os.path.join(BASE_DIR, "config", "weights_manifest.json")
ALGORITHM = "sha256"
WEIGHT_EXTS = (".pth", ".pt", ".dat")
EXCLUDE_DIRS = {"__pycache__", ".git", "node_modules", ".workbuddy", ".arts"}


class WeightsIntegrityError(RuntimeError):
    """Weight integrity verification failed."""

    pass


def _discover():
    """Recursively discover all weight files, returning [(relative path, absolute path), ...] sorted by relative path."""
    found = []
    for root, dirs, files in os.walk(BASE_DIR):
        # prune the traversal list in place, skipping unrelated directories
        dirs[:] = [
            d
            for d in dirs
            if d not in EXCLUDE_DIRS and not d.startswith(".")
        ]
        for f in files:
            if f.lower().endswith(WEIGHT_EXTS):
                ap = os.path.join(root, f)
                rel = os.path.relpath(ap, BASE_DIR).replace(os.sep, "/")
                found.append((rel, ap))
    found.sort(key=lambda x: x[0])
    return found


def compute_sha256(path, chunk_size=1 << 20):
    """Compute SHA-256 in chunks to avoid loading large files into memory at once."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(chunk_size), b""):
            h.update(block)
    return h.hexdigest()


def generate_manifest(manifest_path=None):
    """Scan current weights and write the baseline manifest. Returns the manifest dict.

    Note: manifest_path must default to None and resolve module-level MANIFEST_PATH at runtime. If written as `manifest_path=MANIFEST_PATH`, the default binds to the production path at import time, so overriding wc.MANIFEST_PATH in tests has no effect and test artifacts can overwrite the real baseline (this actually happened: the production manifest was once overwritten by 2 fake test files).
    """
    manifest_path = manifest_path or MANIFEST_PATH
    files = []
    for rel, ap in _discover():
        files.append({"path": rel, "sha256": compute_sha256(ap)})
    manifest = {
        "algorithm": ALGORITHM,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "file_count": len(files),
        "files": files,
    }
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    return manifest


def verify_weights(manifest_path=None):
    """Verify against the baseline manifest: missing manifest, missing file, or hash mismatch raises WeightsIntegrityError.

    Returns the number of files that passed verification.

    manifest_path works like generate_manifest: defaults to None and resolves at runtime to avoid import-time binding.
    """
    manifest_path = manifest_path or MANIFEST_PATH
    if not os.path.exists(manifest_path):
        raise WeightsIntegrityError(
            f"Weight verification manifest not found: {manifest_path}.\n"
            f"Generate the baseline first: python -m config.weights_check generate"
        )
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    expected_alg = manifest.get("algorithm", ALGORITHM)
    if expected_alg != ALGORITHM:
        raise WeightsIntegrityError(
            f"Manifest algorithm {expected_alg} differs from the current expectation {ALGORITHM}; please regenerate the manifest."
        )

    problems = []
    for entry in manifest.get("files", []):
        rel = entry["path"]
        ap = os.path.join(BASE_DIR, rel)
        if not os.path.exists(ap):
            problems.append(f"Missing file: {rel}")
            continue
        actual = compute_sha256(ap)
        expected = entry.get("sha256")
        if actual != expected:
            problems.append(
                f"Hash mismatch: {rel}\n    expected {expected}\n    actual {actual}"
            )

    if problems:
        raise WeightsIntegrityError(
            "Weight integrity verification failed; the service refuses to start:\n- " + "\n- ".join(problems)
        )
    return len(manifest.get("files", []))


if __name__ == "__main__":
    import sys

    cmd = sys.argv[1] if len(sys.argv) > 1 else "verify"
    if cmd == "generate":
        m = generate_manifest()
        print(f"Baseline manifest generated: {MANIFEST_PATH}")
        print(f"Weight file count: {m['file_count']}")
    elif cmd == "verify":
        try:
            n = verify_weights()
            print(f"Weight integrity check passed ✅ ({n} files)")
        except WeightsIntegrityError as e:
            print(str(e), file=sys.stderr)
            sys.exit(1)
    else:
        print("Usage: python -m config.weights_check [generate|verify]", file=sys.stderr)
        sys.exit(2)
