"""Export per-group locked requirement files (plan §3.12).

The report asks for dependency locking split by purpose::

    runtime dependencies
    model dependencies
    ci dependencies
    benchmark dependencies

    [project.optional-dependencies]
    api = [...]
    training = [...]
    benchmark = [...]
    test = [...]

``requirements.lock`` is a flat freeze: correct, but it cannot tell a production
image from a CI image, so every install pulls the GPU stack and the test tools.
This script splits it by group.

How it works - and its limits
-----------------------------
Each group starts from the group's *direct* requirements, then walks
``importlib.metadata.requires()`` to collect the transitive closure, and finally
pins every member to the version recorded in ``requirements.lock``.

That is a closure over *installed* metadata, not a real resolver: it cannot pick
different versions per group the way ``pip-compile`` would. That is fine here -
the point is to stop shipping pytest into production, and every group resolves to
versions that are already known to work together because they came from one
environment. For a fully resolved, reproducible set, use ``pip-compile``.

Which environment, on purpose
-----------------------------
The closure of a group is a property of an installed environment, not of
pyproject.toml: a CPU wheel of torch depends on a different set of packages than
a ``+cu128`` one. So the files are only meaningful as *the freeze of one named
environment*, and ``--freeze`` records that environment in
``requirements.lock`` (``# Frozen-environment: python 3.11 / win32``). Both
subcommands then behave accordingly:

* ``--freeze`` and ``export`` must run in that environment - generating from a
  different interpreter would write files that claim to install the deployment
  stack while describing a different one.
* ``--check`` always verifies the things that cannot vary by machine (every pin
  in a group file agrees with the lock, every line is installable elsewhere), and
  only re-derives the closure when the current interpreter *is* the frozen one.
  Anywhere else it says so instead of reporting a difference that has nothing to
  do with the lock.

Usage::

    python scripts/export_locks.py --freeze        # rewrite requirements.lock
    python scripts/export_locks.py                 # write requirements/*.txt
    python scripts/export_locks.py --check         # verify them
    python scripts/export_locks.py --output DIR    # write somewhere else (tests)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from importlib.metadata import PackageNotFoundError, distribution, requires

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT_DIR = os.path.join(PROJECT_ROOT, "requirements")
LOCK_FILE = os.path.join(PROJECT_ROOT, "requirements.lock")
PYPROJECT = os.path.join(PROJECT_ROOT, "pyproject.toml")

HEADER = """# Generated by scripts/export_locks.py - do not edit by hand.
#
# Group: {group}
# Source: requirements.lock + the `{group}` extra in pyproject.toml
# Versions: the freeze named by requirements.lock's `# Frozen-environment:` line
#
# Install with:  pip install -r requirements/{group}.txt
"""

LOCK_HEADER = """# Dependency freeze of the one environment this project is deployed to.
# Regenerate with `python scripts/export_locks.py --freeze` (make lock-freeze),
# then the per-group files with `make lock`. Do not edit by hand.
#
# Packages installed from a local wheel or a conda build record their original
# source below and are pinned as plain `name==version` above, so this file stays
# installable on a machine that does not have those paths.
# Frozen-environment: {tag}
"""

ENV_TAG_PREFIX = "# Frozen-environment:"


def env_tag() -> str:
    """Identify the interpreter that would generate these files."""
    return f"python {sys.version_info[0]}.{sys.version_info[1]} / {sys.platform}"


def output_dir(argv_dir: str | None = None) -> str:
    """Where the group files live; overridable so tests do not rewrite the repo."""
    return argv_dir or os.environ.get("FIXIMG_LOCK_OUTPUT_DIR") or DEFAULT_OUTPUT_DIR


def _normalise(name: str) -> str:
    """PEP 503 name normalisation, so `Pillow` and `pillow` are one package."""
    return name.strip().lower().replace("_", "-").replace(".", "-")


def _requirement_name(spec: str) -> str:
    """Extract the bare package name from a requirement specifier."""
    text = spec.strip()
    for separator in ("[", "==", ">=", "<=", "~=", "!=", ">", "<", ";", "@", " "):
        index = text.find(separator)
        if index > 0:
            text = text[:index]
    return text.strip()


def iter_lock_lines(path: str | None = None) -> list[str]:
    """The meaningful lines of ``requirements.lock`` (no blanks, comments, flags)."""
    target = path or LOCK_FILE
    if not os.path.exists(target):
        raise SystemExit(f"missing {target}; run `python scripts/export_locks.py --freeze`")
    lines: list[str] = []
    with open(target, encoding="utf-8-sig") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("-"):
                continue
            lines.append(line)
    return lines


def read_lock(lines: list[str] | None = None) -> dict[str, str]:
    """``requirements.lock`` as {normalised name: pinned line}."""
    return {_normalise(_requirement_name(line)): line for line in (lines or iter_lock_lines())}


def lock_env_tag(path: str | None = None) -> str | None:
    """The environment ``requirements.lock`` was frozen from, or None if unrecorded."""
    target = path or LOCK_FILE
    if not os.path.exists(target):
        return None
    with open(target, encoding="utf-8-sig") as handle:
        for raw in handle:
            line = raw.strip()
            if line.startswith(ENV_TAG_PREFIX):
                return line[len(ENV_TAG_PREFIX):].strip()
    return None


def portability_problems(lines: list[str]) -> list[str]:
    """Lock lines another machine cannot install.

    ``pip freeze`` emits ``torch @ file:///D:/Soft/fixoldimg_wheels/torch.whl`` for
    anything installed from a local wheel or a conda build, and those paths exist
    only on the machine that produced the freeze. Left in, they are copied into
    ``requirements/gpu.txt`` and make the documented GPU install fail outright.
    """
    return [line for line in lines if "==" not in line]


def read_groups() -> dict[str, list[str]]:
    """``[project.optional-dependencies]`` from pyproject.toml."""
    try:
        import tomllib  # Python 3.11+
    except ImportError:  # pragma: no cover - older interpreters
        try:
            import tomli as tomllib  # type: ignore[no-redef]
        except ImportError:
            raise SystemExit("Python 3.11+ (or `pip install tomli`) is required") from None

    with open(PYPROJECT, "rb") as handle:
        data = tomllib.load(handle)
    project = data.get("project") or {}
    groups = dict(project.get("optional-dependencies") or {})
    groups["runtime"] = list(project.get("dependencies") or [])
    return groups


def _spec_name_and_scope(spec: str) -> tuple[str, bool]:
    """(normalised name, does this interpreter need it?) for one requirement line.

    Installed metadata mixes unconditional deps with conditionals written for other
    Pythons - gradio declares ``audioop-lts; python_version >= "3.13"``, some
    packages declare ``importlib-metadata; python_version < "3.8"``. Collecting
    those unconditionally put names in ``requirements/runtime.txt`` that no installer
    can resolve on the interpreter the file is meant for, and made the audit red for
    a reason that was purely which interpreter happened to run it.

    Markers are evaluated against *this* interpreter, which is only sound because
    the caller has already checked it is the environment ``requirements.lock`` names.
    """
    from packaging.markers import InvalidMarker, Marker

    name_part, _, marker_part = spec.partition(";")
    name = _normalise(_requirement_name(name_part))
    marker = marker_part.strip()
    if not marker:
        return name, True
    if "extra" in marker:
        # `foo; extra == "dev"` is an optional extra of foo, not a hard dependency.
        return name, False
    try:
        return name, bool(Marker(marker).evaluate())
    except (InvalidMarker, TypeError, ValueError):
        return name, True  # an unreadable marker is kept rather than silently dropped


def closure(roots: list[str]) -> set[str]:
    """Transitive dependency closure of ``roots`` over installed metadata."""
    seen: set[str] = set()
    queue = [_normalise(_requirement_name(r)) for r in roots]
    while queue:
        name = queue.pop()
        if not name or name in seen:
            continue
        seen.add(name)
        try:
            declared = requires(name) or []
        except PackageNotFoundError:
            # Not installed here (e.g. the GPU stack on a CPU box). Keep the
            # name so the group file still lists it, but do not recurse.
            continue
        for spec in declared:
            dependency, in_scope = _spec_name_and_scope(spec)
            if in_scope:
                queue.append(dependency)
    return seen


def render_group(group: str, pinned: dict[str, str], names: set[str]) -> tuple[str, list[str]]:
    """Build the file body; returns (text, missing names)."""
    lines: list[str] = []
    missing: list[str] = []
    for name in sorted(names):
        line = pinned.get(name)
        if line is None:
            missing.append(name)
            continue
        lines.append(line)
    body = HEADER.format(group=group) + "\n".join(lines) + "\n"
    return body, missing


def _require_frozen_environment() -> str:
    """Refuse to generate from an interpreter that is not the lock's environment."""
    tag = lock_env_tag()
    current = env_tag()
    if tag is None:
        raise SystemExit(
            "requirements.lock has no `# Frozen-environment:` line; regenerate it with\n"
            f"    python {os.path.relpath(__file__, PROJECT_ROOT)} --freeze"
        )
    if tag != current:
        raise SystemExit(
            f"this interpreter is {current} but requirements.lock was frozen from {tag}.\n"
            "Generating here would write group files that describe a different "
            "environment\nfrom the one they claim to pin. Run --freeze and the export "
            "in the same\nenvironment (the deployment one), or set "
            "FIXIMG_LOCK_OUTPUT_DIR to a scratch dir."
        )
    return tag


def freeze() -> int:
    """Write ``requirements.lock`` from this interpreter, as installable pins."""
    from importlib.metadata import distributions

    pins: dict[str, tuple[str, str]] = {}
    provenance: list[str] = []
    for dist in distributions():
        name = (dist.metadata["Name"] or "").strip()
        if not name:
            continue
        key = _normalise(name)
        try:
            # `Distribution.info_location` only exists on newer interpreters, and
            # `read_text` raises for the metadata-free installs conda leaves behind.
            raw = dist.read_text("direct_url.json")
        except (OSError, AttributeError, TypeError):
            raw = None
        if raw:
            try:
                info = json.loads(raw)
            except ValueError:
                info = {}
            if (info.get("dir_info") or {}).get("editable"):
                continue  # the project itself, as `pip freeze --exclude-editable` does
            url = str(info.get("url", ""))
            if url.startswith("file:") or url.startswith("/"):
                provenance.append(f"#   {name}=={dist.version} came from {url}")
        pins[key] = (name, dist.version)

    header = LOCK_HEADER.format(tag=env_tag())
    body = "\n".join(f"{name}=={version}" for _key, (name, version) in sorted(pins.items()))
    notes = "\n".join(sorted(provenance))
    with open(LOCK_FILE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header)
        if notes:
            handle.write("#\n")
            handle.write(notes.rstrip("#").rstrip())
            handle.write("\n")
        handle.write(body + "\n")
    print(f"{LOCK_FILE}: {len(pins)} package(s), frozen from {env_tag()}")
    if provenance:
        print(f"normalised {len(provenance)} local-wheel install(s) to name==version")
    return 0


def export(target_dir: str | None = None) -> dict[str, int]:
    _require_frozen_environment()
    out_dir = output_dir(target_dir)
    lines = iter_lock_lines()
    problems = portability_problems(lines)
    if problems:
        print("requirements.lock cannot be installed on another machine:")
        for problem in problems:
            print(f"  {problem}")
        print("run: python scripts/export_locks.py --freeze")
        raise SystemExit(1)

    pinned = read_lock(lines)
    groups = read_groups()
    os.makedirs(out_dir, exist_ok=True)
    summary: dict[str, int] = {}
    unresolved: dict[str, list[str]] = {}

    for group, roots in sorted(groups.items()):
        names = closure(roots)
        body, missing = render_group(group, pinned, names)
        target = os.path.join(out_dir, f"{group}.txt")
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        summary[group] = len(names)
        if missing:
            unresolved[group] = sorted(missing)
        note = f"  ({len(missing)} unpinned)" if missing else ""
        print(f"{group:12s} -> {len(names):3d} package(s){note}")

    if unresolved:
        print(
            "\nUnpinned entries are packages this environment does not have, so "
            "requirements.lock\ncannot carry a version for them. Usually that means "
            "a conditional dependency\nfor another Python version (tomli, async-timeout, "
            "audioop-lts,\nimportlib-metadata), a distribution-name variant "
            "(opencv-python-headless vs\nopencv-python), or an extra that is not "
            "installed here (mypy, tabulate,\npytest-cov). Install them and regenerate:\n"
            "    make lock-freeze && make lock\n"
        )
        for group, names in unresolved.items():
            print(f"  {group}: {', '.join(names)}")
    return summary


def _distribution_installed(name: str) -> bool:
    """Whether a package is importable metadata here (so its closure is knowable)."""
    try:
        distribution(name)
        return True
    except PackageNotFoundError:
        return False


def _file_pins(path: str) -> list[str]:
    """The requirement lines of a generated group file."""
    with open(path, encoding="utf-8") as handle:
        return [line.strip() for line in handle
                if line.strip() and not line.strip().startswith("#")]


def check(target_dir: str | None = None) -> int:
    """Verify the generated files; returns a process exit code.

    Two tiers, so the answer does not depend on which interpreter happens to run
    the suite (see the module docstring):

    * Always, and red on any machine: every pin in a group file must equal the
      lock, every line must be installable elsewhere, and the lock itself must be
      portable. These are pure facts about the committed files.
    * Only in the environment the lock was frozen from, and only for groups whose
      roots are all installed: the byte-for-byte closure, because that is the one
      machine where re-deriving it means the same thing. Elsewhere it is reported
      as skipped, naming both environments.
    """
    out_dir = output_dir(target_dir)
    lines = iter_lock_lines()
    problems = portability_problems(lines)
    if problems:
        print("requirements.lock carries pins another machine cannot install:")
        for problem in problems:
            print(f"  {problem}")
        print("run: python scripts/export_locks.py --freeze")
        return 1

    pinned = read_lock(lines)
    groups = read_groups()
    tag = lock_env_tag()
    strict = tag == env_tag()

    stale: list[str] = []
    drift: list[str] = []
    skipped: list[str] = []

    for group, roots in sorted(groups.items()):
        target = os.path.join(out_dir, f"{group}.txt")
        if os.path.exists(target):
            for line in _file_pins(target):
                name = _normalise(_requirement_name(line))
                if "==" not in line:
                    drift.append(f"{group}: {line!r} is not a plain pin")
                elif pinned.get(name) != line:
                    drift.append(
                        f"{group}: {line!r} != requirements.lock "
                        f"{pinned.get(name) or '<absent>'!r}"
                    )
        if not strict:
            skipped.append(group)
            continue
        missing_roots = [
            _normalise(_requirement_name(root))
            for root in roots
            if not _distribution_installed(_normalise(_requirement_name(root)))
        ]
        if missing_roots:
            skipped.append(f"{group} (not installed: {', '.join(missing_roots)})")
            continue
        body, missing = render_group(group, pinned, closure(roots))
        if missing:
            stale.append(f"{group} ({len(missing)} root(s) unpinned here: "
                         f"{', '.join(sorted(missing))})")
            continue
        if not os.path.exists(target):
            stale.append(f"{group} (missing)")
        elif _file_text(target) != body:
            stale.append(group)

    if not strict:
        print(
            "closure re-derivation skipped: requirements.lock was frozen from "
            f"{tag or '<unrecorded>'}, this interpreter is {env_tag()}"
        )
        print("verified the lock/pin agreement of: " + ", ".join(skipped))
        skipped = []
    if skipped:
        print("not re-derived here (group not installed): " + "; ".join(skipped))
    if drift:
        print("disagrees with requirements.lock:")
        for item in drift:
            print(f"  {item}")
    if stale:
        print("out of date: " + ", ".join(stale))
        print("run: python scripts/export_locks.py")
    if drift or stale:
        return 1
    print("requirements/ agrees with requirements.lock"
          + ("" if strict else " (closure not re-derivable here)"))
    return 0


def _file_text(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the generated files are current")
    parser.add_argument("--freeze", action="store_true",
                        help="rewrite requirements.lock from this interpreter")
    parser.add_argument("--output", default=None,
                        help="directory for the group files (default: requirements/)")
    args = parser.parse_args(argv)
    if args.freeze:
        return freeze()
    if args.check:
        return check(args.output)
    export(args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
